apiVersion: apps/v1
kind: Deployment
metadata:
  name: prova-fastapi
spec:
    replicas: 3
    selector:
      matchLabels:
        app: prova-fastapi
    template:
      metadata:           
        labels:
          app: prova-fastapi
      spec:
        containers:
        - name: prova-fastapi
          image: prova-fastapi 
          ports:
          - containerPort: 8000

