apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: prova-fastapi
  newName: jkvuacamila/prova-fastapi-k8s
  newTag: 1ef5f3fd2bcfc828c6eab5240281848777851bfa
