apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: prova-fastapi
  newName: jkvuacamila/prova-fastapi-k8s
  newTag: d9731c479f761cd0668210571b7a88f65d22f856
